### ISSUE TITLE
Switch to HTTPS

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openbeautyfacts-ruby#2]
HTTPS will soon be live on OBF

**Comment by nicolasleger** [comment]
@teolemon not on openbeautyfacts.org ?

**Comment by teolemon** [comment]
Thanks for checking. We're deploying OBF very soon. Will update when done.

**Comment by teolemon** [comment]
Deployed :-)

**Comment by nicolasleger** [comment]
Done with version 0.1.2, thanks!
