### ISSUE TITLE
Automate the release of the Gem

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openbeautyfacts-ruby#45]
### Who for
- mainteners
- developers
### What
- [x] Automate the release of the Gem

### Why
- Saving time

**Comment by nicolasleger** [comment]
Following instructions from https://andrewm.codes/blog/automating-ruby-gem-releases-with-github-actions/

- Added `RUBYGEMS_AUTH_TOKEN` in project secrets
- Bump to version `0.6.1` with the categories fix to trigger the auto-Pull-Request for release ✅ https://github.com/openfoodfacts/openbeautyfacts-ruby/pull/47
- Check release on RubyGems https://rubygems.org/gems/openbeautyfacts ❌
